name: currency_converter
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.3.2
  flutter_screenutil: ^5.9.0
  dropdown_search: ^5.0.6
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  shimmer: ^3.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  json_serializable: ^6.7.1
  retrofit: ^4.0.3
  retrofit_generator: ^8.0.6
  freezed: ^2.4.6
  cached_network_image: ^3.3.1
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  pretty_dio_logger: ^1.3.1
  awesome_snackbar_content: ^0.1.3
  intl: ^0.18.1

dev_dependencies:
  flutter_gen: ^5.4.0
  bloc_test: ^9.1.6
  hive_generator: ^2.0.1
  build_runner: ^2.4.7
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  mocktail: ^1.0.3

  flutter_lints: ^3.0.1

flutter:
  generate: true
  uses-material-design: true

  assets:
     - assets/images/